language: go

go:
  - 1.14

services:
  - docker

cache:
  directories:
    - $GOPATH/pkg/mod

before_script:
  - docker pull k8s.gcr.io/coredns:1.6.2
  - docker pull registry:2
  - go get -u github.com/google/go-containerregistry/cmd/crane

script:
  - go vet
  - make docker-test
  - make endtoend-test
